spring:
  application:
    name: Project Management

  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://${PMA_DB_HOST}:${PMA_DB_PORT}/${PMA_DB_NAME}
    #username: ${PMA_DB_USERNAME}
    #password: ${PMA_DB_PASSWORD}
    url: jdbc:postgresql://localhost:32768/pma
    username: svc_api
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  server:
    port: 8080
    servlet:
      context-path: /

  logging:
    level:
      org.springframework: INFO
    file: